/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muqing_android_screencapture2gif_helper_gifhelper_FFmpegNativeHelper */

#ifndef _Included_com_muqing_android_screencapture2gif_helper_gifhelper_FFmpegNativeHelper
#define _Included_com_muqing_android_screencapture2gif_helper_gifhelper_FFmpegNativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muqing_android_screencapture2gif_helper_gifhelper_FFmpegNativeHelper
 * Method:    ffmpeg_entry
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_muqing_android_screencapture2gif_helper_gifhelper_FFmpegNativeHelper_ffmpeg_1entry
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
